version: '2.2'

services:
  freeswitch:
    image: "mmtnrw/freeswitch"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    network_mode: host
    privileged: true
    tty: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/share/Freeswitch/config:/config"
      - "/share/Freeswitch/data:/data"
      - "/share/Freeswitch/sounds:/sounds"
    environment:
      TZ: "Europe/Amsterdam"
